workflow update

diff --git a/.github/workflows/sales-analysis.yml b/.github/workflows/sales-analysis.yml
--- a/.github/workflows/sales-analysis.yml
+++ b/.github/workflows/sales-analysis.yml
@@ -42,8 +42,8 @@ jobs:
         echo "Reports Folder:"
         ls -la reports || echo "reports folder not found"
 
-        echo "Visualizations Folder:"
-        ls -la visualizations || echo "visualizations folder not found"
+        echo "Visualization Folder:"
+        ls -la visualization || echo "visualizations folder not found"
 
     - name: Upload Reports
       uses: actions/upload-artifact@v4
