workflow updated

diff --git a/.github/workflows/sales-analysis.yml b/.github/workflows/sales-analysis.yml
--- a/.github/workflows/sales-analysis.yml
+++ b/.github/workflows/sales-analysis.yml
@@ -31,10 +31,24 @@ jobs:
       run: |
         python sales-analysis.py
 
+    - name: Verify Generated Files
+      run: |
+        echo "Current Directory:"
+        pwd
+
+        echo "All Files:"
+        ls -R
+
+        echo "Reports Folder:"
+        ls -la reports || echo "reports folder not found"
+
+        echo "Visualizations Folder:"
+        ls -la visualizations || echo "visualizations folder not found"
+
     - name: Upload Reports
       uses: actions/upload-artifact@v4
       with:
         name: sales-report
         path: |
-          reports/
-          visualizations/
+          reports/**
+          visualizations/**
